export const GET_WISHLIST = "GET_WISHLIST";
export const ADD_WISHLIST_GAME = "ADD_WISHLIST_GAME";
export const DELETE_WISHLIST_GAME_STATE = "  DELETE_WISHLIST_GAME_STATE";
export const DELETE_WISHLIST_GAME_DB = "DELETE_WISHLIST_GAME_DB";
