export const GET_BACKLOG = "GET_BACKLOG";
export const GET_PLAYING = "GET_PLAYING";
export const GET_GENRES = "GET_GENRES";
export const ADD_TO_FEED = "ADD_TO_FEED";
export const GET_FEED = "GET_FEED";
export const GET_PLATFORM_COUNT = "GET_PLATFORM_COUNT";
export const ADD_BACKLOG_GAME = "ADD_BACKLOG_GAME";
export const START_PLAYING_GAME = "START_PLAYING_GAME";
export const START_PLAYING_GAME_DB = "START_PLAYING_GAME_DB";
export const STOP_PLAYING_GAME = "STOP_PLAYING_GAME";
export const ADD_WISHLIST_GAME = "ADD_WISHLIST_GAME";
export const ADD_COMPLETED_GAME = "ADD_COMPLETED_GAME";
export const DELETE_BACKLOG_GAME = "DELETE_BACKLOG_GAME";
export const DELETE_BACKLOG_GAME_DB = "  DELETE_BACKLOG_GAME_DB";
export const DELETE_BACKLOG_GAME_STATE = "DELETE_BACKLOG_GAME_STATE";
export const DELETE_WISHLIST_GAME_STATE = "  DELETE_WISHLIST_GAME_STATE";
export const DELETE_WISHLIST_GAME_DB = "DELETE_WISHLIST_GAME_DB";
export const GET_USER = "GET_USER";
export const GET_COMPLETED = "GET_COMPLETED";
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const GET_WISHLIST = "GET_WISHLIST";
export const MOVE_GAME_FROM_BACKLOG_TO_COMPLETED =
  "MOVE_GAME_FROM_BACKLOG_TO_COMPLETED";
export const MOVE_GAME_FROM_WISHLIST_TO_BACKLOG =
  "MOVE_GAME_FROM_WISHLIST_TO_BACKLOG";
