export const GET_BACKLOG = "GET_BACKLOG";
export const ADD_BACKLOG_GAME = "ADD_BACKLOG_GAME";
export const ADD_WISHLIST_GAME = "ADD_WISHLIST_GAME";
export const DELETE_BACKLOG_GAME = "DELETE_BACKLOG_GAME";
export const GET_USER = "GET_USER";
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const GET_WISHLIST = "GET_WISHLIST";
export const MOVE_GAME_FROM_WISHLIST_TO_BACKLOG =
  "MOVE_GAME_FROM_WISHLIST_TO_BACKLOG";
