export const GET_BACKLOG = "GET_BACKLOG";
export const ADD_BACKLOG_GAME = "ADD_BACKLOG_GAME";
export const DELETE_BACKLOG_GAME_STATE = "DELETE_BACKLOG_GAME_STATE";
export const DELETE_BACKLOG_GAME_DB = "  DELETE_BACKLOG_GAME_DB";
export const MOVE_GAME_FROM_WISHLIST_TO_BACKLOG =
  "MOVE_GAME_FROM_WISHLIST_TO_BACKLOG";
